display_labels = true
chromeless = false

background_color = "#131313"

[button_inactive_colors]
start = "#cdcdcd"
y = "#cdcdcd"
x = "#cdcdcd"
l = "#cdcdcd"
r = "#cdcdcd"
b = "#e73148"
a = "#29a9a1"
z = "#392878"
up = "#555753"
down = "#555753"
left = "#555753"
right = "#555753"
mod_x = "#555753"
mod_y = "#555753"
mod_ls = "#555753"
mod_ms = "#555753"
c_left = "#ddcb3b"
c_right = "#ddcb3b"
c_up = "#ddcb3b"
c_down = "#ddcb3b"

[button_active_colors]
start = "#f0f0f0"
y = "#f0f0f0"
x = "#f0f0f0"
l = "#f0f0f0"
r = "#f0f0f0"
b = "#ff3148"
a = "#29c7be"
z = "#4f3d8b"
up = "#f0f0f0"
down = "#f0f0f0"
left = "#f0f0f0"
right = "#f0f0f0"
mod_x = "#00ebeb"
mod_y = "#00ebeb"
mod_ls = "#00ebeb"
mod_ms = "#00ebeb"
c_left = "#ffea42"
c_right = "#ffea42"
c_up = "#ffea42"
c_down = "#ffea42"
