[package]
name = "b0xx-viewer-rs"
version = "0.1.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
serialport = "3.2.0"
failure = "0.1.5"
failure_derive = "0.1.5"
#rust-pushrod = "0.3.2"
