[package]
name = "b0xx-viewer-rs"
version = "0.6.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
description = "GUI Viewer for B0XX controllers; particularly useful for streaming"
edition = "2021"
build = "build.rs"
license = "MIT/Apache-2.0"

[package.metadata.winres]
OriginalFilename = "b0xx_viewer.exe"
LegalCopyright = "Copyright Mathieu \"@OtaK_\" Amiot © 2020"
ProductName = "B0XX Viewer"

[[bin]]
name = "b0xx_viewer"
path = "src/main.rs"

[dependencies]
serialport = "4.0"
log = "0.4"
rand = { version = "0.8", optional = true }
conrod_core = "0.76"
conrod_winit = "0.76"
conrod_glium = "0.76"
winit = "0.26"
glium = "0.28"
crossbeam-channel = "0.5"
clap = "2.33"
lazy_static = "1.4"
fps_counter = { version = "2.0", optional = true }
rusttype = "0.8"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
rgb = { version = "0.8", features = ["serde"] }
anyhow = "1.0"
thiserror = "1.0"
backoff = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[features]
default = []
fake_serial = ["rand"]
fps = ["fps_counter"]
benchmark = ["fake_serial", "fps"]
win_console = []

[profile.release]
lto = true
codegen-units = 1
