[package]
name = "b0xx-viewer-rs"
version = "0.1.0"
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2018"

[dependencies]
serialport = "3.2.0"
failure = "0.1.5"
failure_derive = "0.1.5"
pretty_env_logger = "0.3.0"
log = "0.4.6"
rand = { version = "0.6.5", optional = true }
conrod_core = "0.65.0"
conrod_winit = "0.65.0"
conrod_glium = "0.65.0"
glium = "0.25.0"

[features]
default = []
fake_serial = ["rand"]
